services:
  risingwave:
    image: risingwavelabs/risingwave:latest
    ports:
      - "4566:4566"
      - "5691:5691"
  
  psql-client:
    image: postgres:latest
    depends_on:
      - risingwave
    entrypoint: [ "tail", "-f", "/dev/null" ]